config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-status/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
    mount Ckeditor::Engine => '/ckeditor'
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'contact-us', to: 'contacts#index', as: 'contacts'
  post 'submit-contact', to: 'contacts#create', as: 'create_contact'

  get 'about-us', to: 'about_us#index', as: 'about_us'

  get 'vehicle_trims', to: 'cars#trims'
  get 'vehicle_makes', to: 'vehicle_makes#index'
  get 'vehicle_models', to: 'vehicle_models#index'
  get 'vehicle_models_active_admin', to: 'vehicle_models#active_admin_index'

  root 'main#index'

  resources :inquiries, only: [:create]

  resources :service_categories, path: '/' do
    member do
      get 'calculator'
      get 'results'
      get 'summary'
    end
  end

  get '/excel_storages/:id/progress', to: 'excel_storages#progress'

  scope :api do
    resources :packages, only: :index
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_password_setup_email, if: :inquiry_generated?

  has_many :inquiries

  def to_s
    self.email
  end

  def send_password_setup_email
    # UserMailer.password_setup(self).deliver_later
  end

  def generate_reset_password_token
    set_reset_password_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.erb
<div class="pull-right btn-group" id="links">
  <%- if controller_name != 'sessions' %>
    <%= link_to t('devise.shared.links.sign_in'), new_session_path(resource_name), class: 'btn btn-link' %>
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to t('devise.shared.links.sign_up'), new_registration_path(resource_name), class: 'btn btn-link' %>
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to t('devise.shared.links.forgot_your_password'), new_password_path(resource_name), class: 'btn btn-link' %>
  <% end -%>
</div>