config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-status/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
    mount Ckeditor::Engine => '/ckeditor'
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'contact-us', to: 'contacts#index', as: 'contacts'
  post 'submit-contact', to: 'contacts#create', as: 'create_contact'

  get 'about-us', to: 'about_us#index', as: 'about_us'

  get 'vehicle_trims', to: 'cars#trims'
  get 'vehicle_makes', to: 'vehicle_makes#index'
  get 'vehicle_models', to: 'vehicle_models#index'
  get 'vehicle_models_active_admin', to: 'vehicle_models#active_admin_index'

  root 'main#index'

  resources :inquiries, only: [:create]

  resources :service_categories, path: '/' do
    member do
      get 'calculator'
      get 'results'
      get 'summary'
    end
  end

  get '/excel_storages/:id/progress', to: 'excel_storages#progress'

  scope :api do
    resources :packages, only: :index
  end
end

app/models/service_category.rb
class ServiceCategory < ActiveRecord::Base
	extend FriendlyId
  friendly_id :identifier, use: [:slugged, :finders]

	mount_uploader :banner_image, BannerUploader
	mount_uploader :homepage_image, SquareUploader

	has_many :services, dependent: :destroy
end

app/controllers/service_categories_controller.rb
class ServiceCategoriesController < ApplicationController
  before_action :fetch_data, only: [:calculator, :results, :summary]
  before_action :set_title, only: [:calculator, :results, :summary]
  before_action :set_variant, only: [:results]

  def show
    if params[:id] != 'insurance'
      @service_category = ServiceCategory.find(params[:id])
      render :show_table
    else
      @insurance_service_category =  ServiceCategory.includes(:services).find('insurance')
      @insurances = @insurance_service_category.services
      @non_motor_insurance_service_category = ServiceCategory.includes(:services).find('insurance-non-motor')
      @non_motor_insurances = @non_motor_insurance_service_category.services
    end
  end

  def results
    @car = Car.find(params[:calculate][:vehicle_trim])
    @packages = @car.packages.includes(:company, :service, :features, coverage_handlers: :coverage).order(service_id: :asc)

    gon.results = {
      car: @car.as_json,
      packages: @packages.map { |package| PackageSerializer.new(package, version: :small) },
      services: @service_category.services.map { |service| ServiceSerializer.new(service, version: :small, short: true) },
      features: Feature.all.map { |feature| FeatureSerializer.new(feature, version: :small) },
      region: params[:calculate][:region],
      service_id: params[:calculate][:service_id].to_i
    }
  end

  def summary
    @car = Car.find(params[:car_id])
    package = Package.includes(:company, :service, :features, coverage_handlers: :coverage).find(params[:package_id])
    @package = ::DeepStruct.new(PackageSerializer.new(package, version: :small).to_hash)
    @region = params[:region]
  end

  private

  def fetch_data
    @service_category = ServiceCategory.find_by(identifier: 'insurance')
    @services = @service_category.services
    @years = Year.order(name: :desc).all
    @companies = Company.all
  end

  def set_title
    @title = "CP Interbroker - Insurance Calculator"
  end

  def set_variant
    request.variant = :mobile if browser.device.mobile?
  end
end

app/helpers/service_categories_helper.rb
module ServiceCategoriesHelper
end

app/views/service_categories/calculator.html.erb
<!-- Insurance Name -->
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <h1 class="text-center"><%= @service_category.name %></h1>
    <hr class="mb-30">
    <div class="caption text-center">
      <%= simple_format(@service_category.description) %>
    </div>
  </div>
</div>

<!-- Calculator -->
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-info calculator">
      <div class="panel-heading">
        <div class="panel-title text-center">
          <%= t('calculator.title') %>
        </div>
      </div>
      <div class="panel-body">
        <div class="row">
          <div id="form" class="col-md-8 col-md-offset-2">
            <%= simple_form_for :calculate, method: :get, url: results_service_category_path('insurance') do |f| %>
              <%= f.input :service_id, as: :hidden, input_html: { value: params[:service_id] } %>
              <%= f.input :year, label: t('attributes.year'), collection: @years, prompt: t('calculator.placeholders.year') %>
              <%= f.input :vehicle_make, label: t('attributes.vehicle_make'), collection: [], prompt: t('calculator.placeholders.vehicle_make') %>
              <%= f.input :vehicle_model, label: t('attributes.vehicle_model'), collection: [], prompt: t('calculator.placeholders.vehicle_model') %>
              <%= f.input :vehicle_trim, label: t('activerecord.attributes.car.trim'), collection: [], prompt: t('calculator.placeholders.vehicle_trim') %>
              <%= f.input :region, as: :radio_buttons, collection:  [[t('calculator.regions.bangkok'), 'bangkok'] ,[t('calculator.regions.other'), 'other']], checked: 'bangkok', item_label_class: "radio-inline", item_wrapper_tag: false, label: false %>
              <%= content_tag :button, type: 'submit', class: 'btn btn-primary btn-block' do %>
                <%= icon "spinner", class: "fa-spin hidden", id: "loader" %>
                <%= content_tag :span, t('calculator.calculate'), id: "loader-text" %>
                <%= content_tag :span, t('calculator.calculating'), id: "loading-text", class: "hidden" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'shared/partners' %>

app/views/service_categories/results.html+mobile.erb
<div class="row">
  <div class="col-md-12">
    <div id="results-panel" class="panel panel-info results">
      <div class="panel-heading">
        <div class="panel-title text-center">
          <%= t('calculator.title') %>
        </div>
      </div>

      <div class="panel-body">
        <div class="panel car-details">
          <table class="table">
            <tr>
              <td><%= @car.year.name %></td>
              <td><%= @car.vehicle_make.name %></td>
              <td><%= @car.vehicle_model.name %></td>
              <td><%= @car.trim %></td>
            </tr>

            <tr>
              <td colspan="4"><%= link_to 'เปลี่ยน', calculator_service_category_path, class: 'btn btn-sm btn-block btn-primary' %></td>
            </tr>
          </table>
        </div>

        <div class="service-buttons btn-group btn-group-justified">
          <template v-for="service in services">
            <a class="btn btn-primary" :class="{ active: hasFilter(service.id) }" v-on:click.prevent="toggleFilter(service.id)">
              {{ service.short_name }}
            </a>
          </template>
        </div>

        <div class="table-header">
          <table class="table">
            <thead>
              <th class="company package-header mobile" @click="setSortOrder('company')"><%= t('calculator.results.insurance_company').chomp("ประกันภัย") %></th>
              <th class="sum package-header mobile" @click="setSortOrder('sum_insured')"><%= t('calculator.results.sum_insured') %></th>
              <th class="price package-header mobile" @click="setSortOrder('final_price')"><%= t('calculator.results.price') %></th>
            </thead>
          </table>
        </div>

        <div class="packages">
          <package v-for="package in computedPackages" :package="package" :features="features" ref="package" v-on:selected="toggleSelected"></package>
        </div>
      </div>

      <div class="compare-button" v-if="comparable" @click="openModal()">เปรียบเทียบแพ็คเกจ</div>

      <modal :visible="modalVisible" :packages="selectedPackages" v-on:close="closeModal()"></modal>
    </div>
  </div>
</div>

<%= render 'service_categories/results/modal' %>
<%= render 'service_categories/results/package' %>

app/views/service_categories/results.html.erb
<div class="row">
  <div class="col-md-12">
    <div id="results-panel" class="panel panel-info results">
      <div class="panel-heading">
        <div class="panel-title text-center">
          <%= t('calculator.title') %>
        </div>
      </div>

      <div class="panel-body">
        <div class="panel car-details">
          <table class="table">
            <tr>
              <td><%= @car.year.name %></td>
              <td><%= @car.vehicle_make.name %></td>
              <td><%= @car.vehicle_model.name %></td>
              <td><%= @car.trim %></td>
              <td><%= link_to 'เปลี่ยน', calculator_service_category_path, class: 'btn btn-sm btn-block btn-primary' %></td>
            </tr>
          </table>
        </div>

        <div class="service-buttons btn-group btn-group-justified">
          <template v-for="service in services">
            <a class="btn btn-primary" :class="{ active: hasFilter(service.id) }" v-on:click.prevent="toggleFilter(service.id)">
              {{ service.name }}
            </a>
          </template>
        </div>

        <div class="table-header">
          <table class="table">
            <thead>
              <th class="package-header"></th>
              <th class="company package-header" @click="setSortOrder('company')">
                <%= t('calculator.results.insurance_company') %>
                <i :class="sortOrderClass('company')" />
              </th>
              <th class="insurance-class package-header" @click="setSortOrder('service')">
                <%= t('calculator.results.insurance_class') %>
                <i :class="sortOrderClass('service')" />
              </th>
              <th class="repair-site package-header" @click="setSortOrder('repair')">
                <%= t('calculator.results.repair_site') %>
                <i :class="sortOrderClass('repair')" />
              </th>
              <th class="sum package-header" @click="setSortOrder('sum_insured')">
                <%= t('calculator.results.sum_insured') %>
                <i :class="sortOrderClass('sum_insured')" />
              </th>
              <th class="first-payment package-header" @click="setSortOrder('excess_payment')">
                <%= t('calculator.results.first_payment') %>
                <i :class="sortOrderClass('excess_payment')" />
              </th>
              <th class="price package-header" @click="setSortOrder('final_price')">
                <%= t('calculator.results.price') %>
                <i :class="sortOrderClass('final_price')" />
              </th>
              <th class="package-header">
                <button class="btn btn-primary btn-block" v-if="comparable" @click="openModal()">เปรียบเทียบแพ็คเกจ</button>
              </th>
            </thead>
          </table>
        </div>

        <div class="packages">
          <package v-for="package in computedPackages" :package="package" :features="features" ref="package" v-on:selected="toggleSelected"></package>
        </div>
      </div>

      <modal :visible="modalVisible" :packages="selectedPackages" v-on:close="closeModal()"></modal>
    </div>
  </div>
</div>

<%= render 'service_categories/results/modal' %>
<%= render 'service_categories/results/package' %>

app/views/service_categories/show.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <h1 class="text-center"><%= @insurance_service_category.name %></h1>
    <hr class="mb-30">
    <div class="row">
      <% @insurances.each do |service| %>
        <div class="col-xs-6 col-md-4 text-center" style="margin-bottom: 20px">
          <%= link_to calculator_service_category_path(@insurance_service_category, service_id: service.id) do %>
            <%= image_tag service.image.url(:medium), width: 150 %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <h1 class="text-center"><%= @non_motor_insurance_service_category.name %></h1>
    <hr class="mb-30">
    <div class="row">
      <% @non_motor_insurances.each do |service| %>
        <div class="col-xs-6 col-md-4 text-center" style="margin-bottom: 20px">
          <% if service.link.blank? %>
            <%= image_tag service.image.url(:medium), width: 150 %>
          <% else %>
            <%= link_to service.link, target: '_blank' do %>
              <%= image_tag service.image.url(:medium), width: 150 %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/service_categories/show_table.html.erb
<!-- Banner -->
<div class="row">
  <div class="col-md-12 top-banner">
    <div class="banner" style="background-image: url('<%= @service_category.banner_image.url %>')"></div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <!-- Title -->
    <h1 class="text-center" style="margin-top: 40px;"><%= @service_category.name %></h1>
    <hr class="mb-30">
  </div>
</div>

<!-- Table -->
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <%= @service_category.description&.html_safe %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <button type="button" class="btn btn-success" onclick="Inquiry.init({hasCloseButton: true})">รายละเอียดเพิ่มเติม!</button>
  </div>
</div>

app/views/service_categories/summary.html.erb
<div id="summary" class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <div class="text-center">
      <h1><%= t('summary.title') %></h1>
    </div>
  </div>

  <div class="col-sm-offset-3 col-sm-6">
    <h3 class="text-center on-small"><%= t('summary.selected_car') %></h3>
    <dl class="dl-horizontal centered">
      <dt><%= t('activerecord.attributes.year.name') %></dt>
      <dd><%= @car.year.name %></dd>
      <dt><%= t('activerecord.models.vehicle_make') %></dt>
      <dd><%= @car.vehicle_make.name %></dd>
      <dt><%= t('activerecord.models.vehicle_model') %></dt>
      <dd><%= @car.vehicle_model.name %></dd>
      <dt><%= t('activerecord.attributes.car.trim') %></dt>
      <dd><%= @car.trim %></dd>
    </dl>
  </div>

  <div class="col-sm-offset-3 col-sm-6">
    <h3 class="text-center on-small"><%= t('summary.selected_package') %></h3>
    <dl class="dl-horizontal centered">
      <dt><%= t('calculator.results.insurance_company') %></dt>
      <dd><%= @package.company.name %></dd>
      <dt><%= t('calculator.results.insurance_class') %></dt>
      <dd><%= @package.service.name %></dd>
      <dt><%= t('calculator.results.sum_insured') %></dt>
      <dd><%= @package.sum_insured.display_value %></dd>
      <dt><%= t('calculator.results.first_payment') %></dt>
      <dd><%= @package.excess_payment.display_value %></dd>
      <dt><%= t('calculator.results.actual_price') %></dt>
      <dd><%= @package.actual_price.display_value %></dd>
      <dt><%= t('calculator.results.final_price') %></dt>
      <dd><%= @package.final_price.display_value %></dd>
    </dl>
  </div>

  <div class="col-sm-offset-3 col-sm-6">
    <h3 class=""><%= t('summary.payment_methods.title') %></h3>
    <ul>
      <li>ชำระผ่านธนาคาร: <a href="<%= asset_url('bank_accounts.png') %>" target="_blank">ดูรายละเอียดบัญชีธนาคาร</a></li>
      <% t('summary.payment_methods.list').each do |l| %>
        <li><%= l %></li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-offset-3 col-sm-6">
    <div>
      <h3><%= t('summary.inquiry') %></h3>
      <div id="inquiry-posted" class="alert alert-success text-center hidden">
        <%= t('mailer.complete') %>
      </div>

      <div id="inquiry-post-fail" class="alert alert-danger text-center hidden">
        <%= t('mailer.fail') %>
      </div>
      <form name="summary-inquiry-form">
        <input type="hidden" name="summary-car-id" id="summary-car-id" value="<%= @car.id %>">
        <input type="hidden" name="summary-package-id" id="summary-package-id" value="<%= @package.id %>">
        <input type="hidden" name="summary-region" id="summary-region" value="<%= @region %>">
        <div class="form-group">
          <label for="summary-name"><%= t('summary.name.title') %></label>
          <input type="text" class="form-control" id="summary-name" placeholder="<%= t('summary.name.placeholder') %>">
          <span id="validation-name" class="hidden text-danger validation"><%= t('summary.name.hint') %></span>
        </div>
        <div class="form-group">
          <label for="summary-email"><%= t('summary.email.title') %></label>
          <input type="email" class="form-control" id="summary-email" placeholder="<%= t('summary.email.placeholder') %>">
          <span id="validation-email" class="hidden text-danger validation"><%= t('summary.email.hint') %></span>
        </div>
        <div class="form-group">
          <label for="summary-phone-number"><%= t('summary.phone.title') %></label>
          <input type="number" class="form-control" id="summary-phone-number" pattern="\\d+" placeholder="<%= t('summary.phone.placeholder') %>">
          <span id="validation-phone-number" class="hidden text-danger validation"><%= t('summary.phone.hint') %></span>
        </div>
        <div class="form-group">
          <label for="summary-message"><%= t('summary.message.title') %></label>
          <textarea class="form-control" name="summary-message" id="summary-message" rows="5" placeholder="<%= t('summary.message.placeholder') %>"></textarea>
          <span id="validation-message" class="hidden text-danger validation"><%= t('summary.message.hint') %></span>
        </div>
        <div class="form-group">
          <button id="submit-button" type="button" class="btn btn-success btn-block"><%= t('summary.submit') %></button>
        </div>
      </form>
    </div>
  </div>
</div>