config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-status/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
    mount Ckeditor::Engine => '/ckeditor'
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'contact-us', to: 'contacts#index', as: 'contacts'
  post 'submit-contact', to: 'contacts#create', as: 'create_contact'

  get 'about-us', to: 'about_us#index', as: 'about_us'

  get 'vehicle_trims', to: 'cars#trims'
  get 'vehicle_makes', to: 'vehicle_makes#index'
  get 'vehicle_models', to: 'vehicle_models#index'
  get 'vehicle_models_active_admin', to: 'vehicle_models#active_admin_index'

  root 'main#index'

  resources :inquiries, only: [:create]

  resources :service_categories, path: '/' do
    member do
      get 'calculator'
      get 'results'
      get 'summary'
    end
  end

  get '/excel_storages/:id/progress', to: 'excel_storages#progress'

  scope :api do
    resources :packages, only: :index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = ContactUsRecord.new
  end

  def create
    @contact = ContactUsRecord.create(permitted_params)
    ContactMailer.contact_email(@contact).deliver_later
    redirect_to contacts_path, notice: t('mailer.complete')
  end

  private

  def permitted_params
    params.require(:contact_us_record).permit(:name, :email, :phone_number, :subject, :message)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<!-- Contact Us -->
<% if flash[:notice] %>
  <div class="alert alert-success text-center">
    <%= flash[:notice] %>
  </div>
<% end %>

<!-- Banner -->
<div class="row">
  <div class="col-md-12 top-banner">
    <div class="banner" style="background-image: url('<%= asset_url('contact_us.png') %>')"></div>
  </div>
</div>

<!-- Title and Description-->
<div class="row section">
  <div class="col-md-offset-1 col-md-10">
    <h1 class="text-center"><%= t('contact.title') %></h1>
    <h3 class="text-center"><%= t('contact.subheading')%></h3>
    <hr class="mb-25">
    <p><%= t('contact.description').html_safe %></p>
  </div>
</div>

<!-- Map and Details/Form Row -->
<div class="row section">
  <!-- Map Column -->
  <div class="col-xs-12 col-md-6">
    <div class="map-container">
      <iframe src="<%= ENV['GOOGLE_MAPS_LINK'] %>" height="250" frameborder="0" style="border: 0; width: 100%;" allowfullscreen></iframe>
    </div>
  </div>

  <!-- Details/Form Column -->
  <div class="col-xs-12 col-md-6">
    <div style="margin-left: 20px">
      <div class="row contact-details" style="margin-top: 25px;">
        <div class="col-md-8">
          <!-- Social Links -->
          <%= icon('share-alt', class: "fa-lg fa-fw")%>
          <%= link_to ENV['FACEBOOK_LINK'], target: '_blank', style: "text-decoration: none;" do %>
            <%= image_tag "facebook.png", class: "contact-social-logo"%>
          <% end %>
          <%= link_to ENV['LINE_LINK'], target: '_blank' do %>
            <%= image_tag "line.png", class: "contact-social-logo"%>
          <% end %>
        </div>
      </div>
      <div class="row contact-details">
        <div class="col-xs-12">
          <!-- Phone Number -->
          <%= icon('phone', class: "fa-lg fa-fw") %> <a href="tel:027109129">02-710-9129</a>
        </div>
      </div>
      <div class="row contact-details">
        <div class="col-xs-12">
          <!-- Fax Numbers -->
          <%= icon('fax', class: "fa-lg fa-fw") %> <span>02-323-2861, 02-323-2866</span>
        </div>
      </div>
      <div class="row contact-details">
        <div class="col-xs-12">
          <!-- Email -->
          <%= icon('envelope', class: "fa-lg fa-fw") %> <a href="mailto:chaipan.nk_cpinter@hotmail.com">chaipan.nk_cpinter@hotmail.com</a>
        </div>
      </div>
      <div class="row contact-details">
        <div class="col-xs-12 col-sm-7 col-md-9">
          <table>
            <tr>
              <td style="vertical-align: top;"><%= icon('home', class: "fa-lg fa-fw") %></td>
              <td style="padding-left: 4px;"><span><b>บริษัท ซี พี อินเตอร์ โบรคเกอร์ จำกัด</b><br> เลขที่ 36/1 (ข้างขนส่งบางปู) ถ.สุขุมวิท ต.บางปูใหม่ อ.เมือง จังหวัดสมุทรปราการ  รหัสไปรษณีย์ 10280</span></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row section">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <hr class="mb-25">
    <h3 class="text-center" style="margin-bottom: 25px;"><%= t('contact.form_title')%></h3>
    <!-- Start Form -->
    <%= simple_form_for @contact, url: create_contact_path do |f| %>
      <%= f.input :name, label: false, placeholder: t('contact.form_name') %>
      <%= f.input :email, label: false, placeholder: t('contact.form_email') %>
      <%= f.input :phone_number, label: false, placeholder: t('contact.form_telephone') %>
      <%= f.input :subject, label: false, placeholder: t('contact.form_subject') %>
      <%= f.input :message, as: :text, label: false, placeholder: t('contact.form_message'), input_html: { rows: 5 } %>
      <%= f.submit t('contact.form_submit'), class: 'btn btn-primary btn-block' %>
    <% end %>
    <!-- end Form -->
  </div>
</div>