config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-status/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
    mount Ckeditor::Engine => '/ckeditor'
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'contact-us', to: 'contacts#index', as: 'contacts'
  post 'submit-contact', to: 'contacts#create', as: 'create_contact'

  get 'about-us', to: 'about_us#index', as: 'about_us'

  get 'vehicle_trims', to: 'cars#trims'
  get 'vehicle_makes', to: 'vehicle_makes#index'
  get 'vehicle_models', to: 'vehicle_models#index'
  get 'vehicle_models_active_admin', to: 'vehicle_models#active_admin_index'

  root 'main#index'

  resources :inquiries, only: [:create]

  resources :service_categories, path: '/' do
    member do
      get 'calculator'
      get 'results'
      get 'summary'
    end
  end

  get '/excel_storages/:id/progress', to: 'excel_storages#progress'

  scope :api do
    resources :packages, only: :index
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer row">
  <div class="col-xs-12" style="padding: 0px;">
    <div class="row footer-content">
      <div class="col-md-4 info">
        <div class="vertical-align-middle">
          <p class="footer-social">
            <%= link_to ENV['FACEBOOK_LINK'], target: '_blank' do %>
              <%= image_tag "facebook.png", class: "footer-social-logo" %>
            <% end %>
            <%= link_to ENV['LINE_LINK'], target: '_blank' do %>
              <%= image_tag "line.png", class: "footer-social-logo" %>
            <% end %>
          </p>
          <p>
            <i class="fa fa-phone"></i> <a href="tel:<%= ENV['PHONE_NUMBER'] %>"><%= ENV['PHONE_NUMBER'] %></a>
            <br>
            <i class="fa fa-fax"></i> <%= ENV['FAX_NUMBER_1'] %>, <%= ENV['FAX_NUMBER_2'] %>
          </p>
          <p>
            <i class="fa fa-envelope"></i> <a href="mailto:<%= ENV['EMAIL_ADDRESS'] %>"><%= ENV['EMAIL_ADDRESS'] %></a>
          </p>
        </div>
      </div>
      <div class="col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-3 info">
        <div class="vertical-align-middle">
          <p>
            <i class="fa fa-home"></i>
            <span>บริษัท ซี พี อินเตอร์ โบรคเกอร์ จำกัด<br> เลขที่ 36/1 (ข้างขนส่งบางปู) ถ.สุขุมวิท ต.บางปูใหม่ อ.เมือง จังหวัดสมุทรปราการ  รหัสไปรษณีย์ 10280</span>
          </p>
        </div>
      </div>
      <div class="col-md-2 col-md-offset-1 col-xs-4 col-xs-offset-4 col-sm-2 col-sm-offset-5 info">
        <div class="vertical-align-middle">
          <div class="thumbnail">
            <%= image_tag 'license.png' %>
          </div>
        </div>
      </div>
    </div>
    <div class="row copyright">
      <div class="col-xs-12 info">
        <div class="vertical-align-middle">
          <p>
            CP Interbroker <i class="fa fa-copyright"></i> 2016 - Powered By <%= link_to 'Cognitive Creations', 'http://cognitivecreations.co', target: '_blank' %>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header row" style="margin: 10px -15px 8px -15px;">
  <div class="col-md-3 col-xs-4">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', class: 'cp-logo' %>
    <% end %>
  </div>
  <div class="col-md-6 col-md-offset-3 col-xs-8">
    <table align="right" style="width: 100%; height: 80px;">
      <tbody>
        <tr>
          <td style="text-align: right; vertical-align: middle; padding: 5px; border-radius: 10px; padding-right: 0px;" class="">
            <div class="container-fluid">
              <!-- Social Stuff -->
              <div class="row" style="margin-top: 5px;">
                <div class="col-xs-12">
                  <%= link_to ENV['FACEBOOK_LINK'], target: '_blank' do %>
                    <%= image_tag "facebook.png", class: "social-logo" %>
                  <% end %>
                  <%= link_to ENV['LINE_LINK'], target: '_blank' do %>
                    <%= image_tag "line.png", class: "social-logo" %>
                  <% end %>
                </div>
              </div>
              <div class="row phone-number">
                <div class="col-xs-12">
                  <span>
                    <%= icon('phone', class: 'fa-1x') %> <a href="tel:<%= ENV['PHONE_NUMBER'] %>"><%= ENV['PHONE_NUMBER'] %></a>
                  </span>
                </div>
              </div>
              <div class="row contact-box">
                <div class="col-sm-12">
                  <span>
                    <%= t('header.opening_weekdays')%> 9.00 - 18.00<br>
                    <%= t('header.opening_weekends')%> 9.00 - 15.00
                  </span>
                </div>
              </div>

            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand <%= 'active' if params[:controller] == "main" %>" href="/" data-toggle="tooltip" title="<%= t('navbar.home') %>" data-placement="bottom"><%= icon('home') %> <span class="visible-xs visible-sm navbar-home"><%= t('navbar.home') %></span></a>
    </div>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <%= content_tag :li, class: ['calculator', 'results', 'summary'].include?(params[:action]) ? 'active' : nil do %>
          <%= link_to t('navbar.insurance_calculator'), calculator_service_category_path(@navbar[:insurance]) %>
        <% end %>

        <% @navbar.each do |key, value| %>
          <%= content_tag :li, class: params[:action] == 'show' && params[:id] == value.identifier ? 'active' : nil do %>
            <%= link_to value.name, service_category_path(value) %>
          <% end %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li <%= 'class=active' if params[:controller] == 'about_us' %>><%= link_to t('navbar.about_us'), about_us_path %></li>
        <li <%= 'class=active' if params[:controller] == 'contacts' %>><%= link_to t('navbar.contact_us'), contacts_path %></li>

        <% if user_signed_in? %>
          <li class="dropdown <%= 'active' if params[:controller].match(/^devise/) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('navbar.sign_out'), destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li <%= "class=active" if params[:controller].match(/^devise/) %> >
            <%= link_to t('navbar.sign_in'), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="jyP9gd4pme9pP51JXsIf3YVKxM1x2rnZv2w_xpcRUIQ" />

    <title><%= @title.present? ? @title : 'CP Interbroker' %></title>
    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag 'application', "data-turbolinks-track": "reload" %>
    <%= csrf_meta_tags %>

    <% if Rails.env.production? %>
      <%= render 'shared/google_tag_manager' unless ENV['GTM_CONTAINER_ID'].nil? %>
    <% end %>
  </head>

  <body class='<%= "#{params[:controller].dasherize}-#{params[:action].dasherize}" %>'>
    <% if Rails.env.production? %>
      <%= render 'shared/google_tag_manager_no_script' unless ENV['GTM_CONTAINER_ID'].nil? %>
    <% end %>

    <%= Gon::Base.render_data %>

    <div class="container outer-container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/navbar' %>

      <div class="row">
        <div class="col-xs-12">
          <div class="margin-for-footer">
            <div class="content-container container-fluid">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>

      <%= render 'layouts/footer' %>
      <%= render 'shared/inquiry' %>
    </div>
  </body>
</html>